services:
  - type: web
    name: rd-store
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: SHOPEE_APP_ID
        sync: false
      - key: SHOPEE_SECRET
        sync: false
